---
title: "Lewis Hurricane Duck"
output: html_document
date: "2022-08-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "code"
output: html_document
date: "2022-08-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#loading the libraries
library(tidyverse)
library(janitor)
library(here)
library(patchwork)
```


```{r}
# reading in the data 
bq1 <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "QuebradaCuenca1-Bisley.csv"), na = "-9999", show_col_types = FALSE) %>%
  clean_names() %>% 
  mutate(site = "BQ1")

bq2 <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "QuebradaCuenca2-Bisley.csv"), na = "-9999", show_col_types = FALSE) %>%
  clean_names()%>% 
  mutate(site = "BQ2")

bq3 <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "QuebradaCuenca3-Bisley.csv"), na = "-9999", show_col_types = FALSE) %>%
  clean_names() %>% 
  mutate(site = "BQ3")

prm <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "RioMameyesPuenteRoto.csv"), na = "-9999",  show_col_types = FALSE) %>%
  clean_names()%>% 
  mutate(site = "PRM")


lef_table <- bind_rows(bq1, bq2, bq3, prm) %>%
  mutate(sample_date = lubridate::ymd(sample_date)) %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  mutate(month = lubridate::month(sample_date)) %>%
  mutate(str_my = paste(year, month)) %>%
  mutate(str_ym_date = lubridate::ym(str_my)) %>%
  mutate(no3_n = as.numeric(no3_n)) %>%
  mutate(k = as.numeric(k)) %>%
  select(sample_date, sample_id, sample_time, no3_n, k, year, month, site, str_ym_date)
```

```{r}

lef_table_subset_sept <- lef_table %>%
  filter(str_ym_date > '1988-8-01' & str_ym_date < '1990-10-01')
  
graph_data <- lef_table_subset_sept %>%
  group_by(str_ym_date, site) %>%
  summarise(mean_k = mean(k, na.rm = TRUE),
            mean_no_3 = mean(no3_n, na.rm = TRUE))

graph_data_test <- lef_table_subset_sept %>%
  group_by(str_ym_date, site) %>%
  summarise(mean_k = mean(k, na.rm = TRUE),
            mean_no_3 = mean(no3_n, na.rm = TRUE)) 

graph_data_test_highlight <- graph_data_test %>%
  group_by(site) %>%
  mutate(max_k=ifelse(mean_k==max(mean_k), "1", "0"))

ggplot(data = graph_data_test_highlight, aes(x = str_ym_date, y = mean_k, fill = max_k)) + 
  geom_col() +
  facet_wrap(~site) +
  labs(x = "Date",
       y = "Mean Potassium (K) in mg/L",
       title = "Mean Potassium levels from September 1988 to 1990",
       subtitle = "Potassium spiked sharply during Hurricane Hugo (denoted in red), fell in the following month, rose back up to elevated levels, and then slowly started to return to baseline") + 
  theme(panel.background = element_rect(fill = "white")) +
  scale_fill_manual(values = c("1"="tomato", "0"="gray" ), guide = FALSE )
```


