---
title: "code"
output: html_document
date: "2022-08-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(patchwork)

q1 <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "QuebradaCuenca1-Bisley.csv"), na = "-9999") %>%
  clean_names()

q2 <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "QuebradaCuenca2-Bisley.csv"), na = "-9999") %>%
  clean_names()

q3 <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "QuebradaCuenca3-Bisley.csv"), na = "-9999") %>%
  clean_names()

prm <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "RioMameyesPuenteRoto.csv"), na = "-9999") %>%
  clean_names()
```



# Ata Code Chunk

```{r}

```



# Elise Code Chunk

```{r}

```



# Lewis Code Chunk

```{r}
# Changing class of date to dateTime



q1_tidy <- q1 %>% 
  mutate(sample_date = lubridate::ymd(sample_date)) %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  mutate(month = lubridate::month(sample_date)) %>% 
  select(sample_id, sample_date, sample_time, no3_n, k, year, month) %>%
  mutate(k = as.numeric(k))

q2_tidy <- q2 %>% 
  mutate(sample_date = lubridate::ymd(sample_date)) %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  mutate(month = lubridate::month(sample_date)) %>% 
  select(sample_id, sample_date, sample_time, no3_n, k, year, month) %>%
  mutate(k = as.numeric(k))


q3_tidy <- q3 %>% 
  mutate(sample_date = lubridate::ymd(sample_date)) %>% 
  mutate(year = lubridate::year(sample_date)) %>%
  mutate(month = lubridate::month(sample_date)) %>% 
  select(sample_id, sample_date, sample_time, no3_n, k, year, month) %>%
  mutate(k = as.numeric(k))

prm_tidy <- prm %>% 
  mutate(sample_date = lubridate::ymd(sample_date)) %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  mutate(month = lubridate::month(sample_date)) %>% 
  select(sample_id, sample_date, sample_time, no3_n, k, year, month) %>%
  mutate(k = as.numeric(k))

all_sites_select_years <- full_join(q1_tidy, q2_tidy) |> 
  full_join(q3_tidy) |> 
  full_join(prm_tidy) |> 
  filter(year >= 1987,
         year <= 1995) |>
  mutate(month_year = lubridate::ym(sample_date))

all_sites_select_years |> 
  group_by(month, year, sample_id) |> 
  summarize(mean_k = mean(k, na.rm = TRUE))


ggplot(data = all_sites_select_years, aes(x = sample_date, y = k)) +
  geom_line(aes(color = sample_id))
```



# Victoria Code Chunk

```{r}

```



# Wade Code Chunk

```{r}

# Changing class of date to dateTime

q1_ws <- q1 %>% 
  mutate(sample_date = lubridate::ymd(sample_date)) %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  mutate(month = lubridate::month(sample_date)) %>% 
  mutate(k = as.numeric(k)) %>%
  mutate(no3_n = as.numeric(no3_n)) %>%
  select(sample_id, sample_date, sample_time, no3_n, k, year, month)

q2_ws <- q2 %>% 
  mutate(sample_date = lubridate::ymd(sample_date)) %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  mutate(month = lubridate::month(sample_date)) %>% 
  mutate(k = as.numeric(k)) %>%
  mutate(no3_n = as.numeric(no3_n)) %>%
  select(sample_id, sample_date, sample_time, no3_n, k, year, month)


q3_ws <- q3 %>% 
  mutate(sample_date = lubridate::ymd(sample_date)) %>% 
  mutate(year = lubridate::year(sample_date)) %>%
  mutate(month = lubridate::month(sample_date)) %>% 
  mutate(k = as.numeric(k)) %>%
  mutate(no3_n = as.numeric(no3_n)) %>%
  select(sample_id, sample_date, sample_time, no3_n, k, year, month)


prm_ws <- prm %>% 
  mutate(sample_date = lubridate::ymd(sample_date)) %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  mutate(month = lubridate::month(sample_date)) %>% 
  mutate(k = as.numeric(k)) %>%
  mutate(no3_n = as.numeric(no3_n)) %>%
  select(sample_id, sample_date, sample_time, no3_n, k, year, month)


joined_data <- q1_ws %>% 
  full_join(q2_ws) %>% 
  full_join(q3_ws) %>% 
  full_join(prm_ws)

summarised_data <- joined_data %>% 
  group_by(sample_id, year) %>% 
  summarise(mean_no3 = mean(no3_n, na.rm = TRUE),
            mean_k = mean(k, na.rm = TRUE))


no3 <- ggplot(data = summarised_data, aes(x = year, y = mean_no3)) +
  geom_line(aes(color = sample_id)) +
  geom_vline(xintercept = (1989))

k <- ggplot(data = summarised_data, aes(x = year, y = mean_k)) +
  geom_line(aes(color = sample_id)) +
  geom_vline(xintercept = (1989))



joined_sites_mean <- joined_data %>% 
  group_by(sample_id, year) %>% 
  summarize(mean_k = mean(k, na.rm = TRUE),
            mean_no3 = mean(no3_n, na.rm = TRUE))




(no3 / k)

```





