---
title: "Hurricane Duck Problem 2"
output: html_document
date: "2022-08-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#loading the libraries
library(tidyverse)
library(janitor)
library(here)
library(patchwork)
```


```{r}
# reading in the data 

#site BQ1
bq1 <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "QuebradaCuenca1-Bisley.csv"), na = "-9999", show_col_types = FALSE) %>%
  clean_names() %>% 
  mutate(site = "BQ1")

#site BQ2
bq2 <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "QuebradaCuenca2-Bisley.csv"), na = "-9999", show_col_types = FALSE) %>%
  clean_names()%>% 
  mutate(site = "BQ2")

#site BQ3
bq3 <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "QuebradaCuenca3-Bisley.csv"), na = "-9999", show_col_types = FALSE) %>%
  clean_names() %>% 
  mutate(site = "BQ3")

#site BQ4
prm <- read_csv(here("/courses", "EDS214", "hurricaneducks", "raw_data_all", "RioMameyesPuenteRoto.csv"), na = "-9999",  show_col_types = FALSE) %>%
  clean_names()%>% 
  mutate(site = "PRM")

#COMBINING THE SITES AND CLEARNING THE DATA
lef_table <- bind_rows(bq1, bq2, bq3, prm) %>% #since all of the columns are the same, we can combine all of the rows using bind_rows()
  mutate(sample_date = lubridate::ymd(sample_date)) %>% #convert data to ISO format
  mutate(year = lubridate::year(sample_date)) %>% #create new year column
  mutate(month = lubridate::month(sample_date)) %>% #create new month column
  mutate(str_my = paste(year, month)) %>% #create new column with month and year data
  mutate(str_ym_date = lubridate::ym(str_my)) %>% #convert above column to ISO format
  mutate(no3_n = as.numeric(no3_n)) %>% #make nitrate nitrogen numeric across all sites
  mutate(k = as.numeric(k)) %>% #make potassium numeric across all sites
  select(sample_date, sample_id, sample_time, no3_n, k, year, month, site, str_ym_date) #select columns of interest
```

```{r}
#filter to months of interest
lef_table_subset_sept <- lef_table %>%
  filter(str_ym_date > '1988-8-01' & str_ym_date < '1990-10-01')

#group by date and site to summarize the mean potassium value for each site and each date
graph_data <- lef_table_subset_sept %>%
  group_by(str_ym_date, site) %>%
  summarise(mean_k = mean(k, na.rm = TRUE),
            mean_no_3 = mean(no3_n, na.rm = TRUE))

#add in a column that identifies hurricane hugo 
graph_data_with_hugo_highlight <- graph_data %>%
  group_by(site) %>%
  mutate(hugo = ifelse(str_ym_date == lubridate::ymd("1989-09-01"), "1", "0"))

#creating the plot for potassium (K)
ggplot(data = graph_data_with_hugo_highlight, aes(x = str_ym_date, y = mean_k, fill = hugo)) +
  geom_col() +
  facet_wrap(~site) +
  labs(x = "Date",
       y = "Mean Potassium (K) in mg/L",
       title = "Mean Potassium levels from September 1988 to 1990",
       subtitle = "Potassium spiked following Hurricane Hugo (denoted in red), fell three months later, rose back up to elevated levels, and then slowly started to return to baseline") + 
  theme(panel.background = element_rect(fill = "white")) +
  scale_fill_manual(values = c("1"="tomato", "0"="gray40" ), guide = FALSE)

#saving the plot
ggsave(here("potassium_by_site_bar_chart.jpg"))
```


```{r}
#creating the plot for nitrate nitrogen (no_3)
ggplot(data = graph_data_with_hugo_highlight, aes(x = str_ym_date, y = mean_no_3, fill = hugo)) + 
  geom_col() +
  facet_wrap(~site) +
  labs(x = "Date",
       y = "Mean Nitrate Nitrogen (µg/L)",
       title = "Mean Nitrate Nitrogen levels from September 1988 to 1990",
       subtitle = "Nitrate Nitrogen levels fell sharply during Hurricane Hugo (denoted in red) and then oscillated in the following months") + 
  theme(panel.background = element_rect(fill = "white")) +
  scale_fill_manual(values = c("1"="tomato", "0"="gray40" ), guide = FALSE)

#saving the plot
ggsave(here("nitrate_by_site_bar_chart.jpg"), height = 10, width = 12)
```


